---
- name: This playbook will setup environment for PHP development
  hosts: lamp_desk
  sudo: yes

  vars_files:
    - vars/main.yml
    - vars/lamp.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=86400
    - name: Ensure user exist
      user: name={{ user_name }} state=present generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
    - name: Ensure www folder exists
      file: path={{ user_folder }} state=directory

  roles:
    - mysql
    - apache
